# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: GitHub Action for ktlint
      uses: yutailang0119/action-ktlint@v1.0.0
      with:
      # The file path of the XML lint report
        xml_path: build/ktlint-report-in-checkstyle-format.xml 
    - name: Gradle Command
      uses: eskatos/gradle-command-action@v1
      with:
        # Path to the Gradle Wrapper directory
        wrapper-directory: gradle/wrapper
        # Gradle command line arguments, see gradle --help
        arguments: build
